// Generated by Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
#ifndef RANDARULESOFGOLF_SWIFT_H
#define RANDARULESOFGOLF_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RANDARulesOfGolf",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("Answer")
@interface Answer : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class Question;
@class NSSet;

@interface Answer (SWIFT_EXTENSION(RANDARulesOfGolf))
- (void)addQuestionObject:(Question * _Nonnull)value;
- (void)removeQuestionObject:(Question * _Nonnull)value;
- (void)addQuestion:(NSSet * _Nonnull)values;
- (void)removeQuestion:(NSSet * _Nonnull)values;
@end

@class NSString;
@class NSDate;

@interface Answer (SWIFT_EXTENSION(RANDARulesOfGolf))
@property (nonatomic, copy) NSString * _Nullable codename;
@property (nonatomic) BOOL isCorrect;
@property (nonatomic, copy) NSString * _Nullable language;
@property (nonatomic, copy) NSDate * _Nullable lastModified;
@property (nonatomic) int16_t position;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, strong) NSSet * _Nullable question;
@end


SWIFT_CLASS_NAMED("BaseRandaEntity")
@interface BaseRandaEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface BaseRandaEntity (SWIFT_EXTENSION(RANDARulesOfGolf))
@property (nonatomic, copy) NSString * _Nullable guid;
@end


SWIFT_CLASS_NAMED("BaseRuleForm")
@interface BaseRuleForm : BaseRandaEntity
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class Clarification;
@class NSIndexSet;
@class NSOrderedSet;

@interface BaseRuleForm (SWIFT_EXTENSION(RANDARulesOfGolf))
- (void)insertObject:(Clarification * _Nonnull)value inClarificationsAtIndex:(NSInteger)idx;
- (void)removeObjectFromClarificationsAtIndex:(NSInteger)idx;
- (void)insertClarifications:(NSArray<Clarification *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeClarificationsAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInClarificationsAtIndex:(NSInteger)idx withObject:(Clarification * _Nonnull)value;
- (void)replaceClarificationsAtIndexes:(NSIndexSet * _Nonnull)indexes withClarifications:(NSArray<Clarification *> * _Nonnull)values;
- (void)addClarificationsObject:(Clarification * _Nonnull)value;
- (void)removeClarificationsObject:(Clarification * _Nonnull)value;
- (void)addClarifications:(NSOrderedSet * _Nonnull)values;
- (void)removeClarifications:(NSOrderedSet * _Nonnull)values;
@end


@interface BaseRuleForm (SWIFT_EXTENSION(RANDARulesOfGolf))
@property (nonatomic, copy) NSString * _Nullable codename;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSString * _Nullable edition;
@property (nonatomic) float floatFullNumber;
@property (nonatomic, copy) NSString * _Nullable number;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) NSOrderedSet * _Nullable clarifications;
@end



SWIFT_CLASS_NAMED("Clarification")
@interface Clarification : BaseRuleForm
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Clarification (SWIFT_EXTENSION(RANDARulesOfGolf))
@property (nonatomic, copy) NSString * _Nullable crossLinkText;
@property (nonatomic, strong) BaseRuleForm * _Nullable parent;
@end


SWIFT_CLASS_NAMED("Rule")
@interface Rule : BaseRuleForm
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CommitteeProcedure")
@interface CommitteeProcedure : Rule
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface CommitteeProcedure (SWIFT_EXTENSION(RANDARulesOfGolf))
@property (nonatomic, copy) NSString * _Nullable committeeParentNumber;
@end



SWIFT_CLASS_NAMED("Definition")
@interface Definition : BaseRandaEntity
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface Definition (SWIFT_EXTENSION(RANDARulesOfGolf))
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSDate * _Nullable lastUpdated;
@property (nonatomic, copy) NSString * _Nullable title;
@end

@class NSCoder;

SWIFT_CLASS("_TtC16RANDARulesOfGolf11ImageTVCell")
@interface ImageTVCell : UITableViewCell
- (void)awakeFromNib;
- (void)prepareForReuse;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("Language")
@interface Language : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface Language (SWIFT_EXTENSION(RANDARulesOfGolf))
@property (nonatomic, copy) NSString * _Nullable displayName;
@property (nonatomic, copy) NSString * _Nullable englishName;
@end





SWIFT_CLASS("_TtC16RANDARulesOfGolf14NetworkManager")
@interface NetworkManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface NetworkManager (SWIFT_EXTENSION(RANDARulesOfGolf)) <NSURLSessionDataDelegate>
@end


SWIFT_CLASS("_TtC16RANDARulesOfGolf14NumberedTVCell")
@interface NumberedTVCell : UITableViewCell
- (void)awakeFromNib;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC16RANDARulesOfGolf23PlainTVHeaderFooterView")
@interface PlainTVHeaderFooterView : UITableViewHeaderFooterView
- (void)awakeFromNib;
- (nonnull instancetype)initWithReuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("Question")
@interface Question : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface Question (SWIFT_EXTENSION(RANDARulesOfGolf))
- (void)addAnswersObject:(Answer * _Nonnull)value;
- (void)removeAnswersObject:(Answer * _Nonnull)value;
- (void)addAnswers:(NSSet * _Nonnull)values;
- (void)removeAnswers:(NSSet * _Nonnull)values;
@end

@class Quiz;

@interface Question (SWIFT_EXTENSION(RANDARulesOfGolf))
@property (nonatomic, copy) NSString * _Nullable codename;
@property (nonatomic, copy) NSString * _Nullable explanation;
@property (nonatomic, copy) NSString * _Nullable imageURL;
@property (nonatomic, copy) NSString * _Nullable language;
@property (nonatomic, copy) NSDate * _Nullable lastModified;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, strong) NSSet * _Nullable answers;
@property (nonatomic, strong) Quiz * _Nullable quiz;
@end


SWIFT_CLASS_NAMED("Quiz")
@interface Quiz : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface Quiz (SWIFT_EXTENSION(RANDARulesOfGolf))
- (void)addQuestionsObject:(Question * _Nonnull)value;
- (void)removeQuestionsObject:(Question * _Nonnull)value;
- (void)addQuestions:(NSSet * _Nonnull)values;
- (void)removeQuestions:(NSSet * _Nonnull)values;
@end


@interface Quiz (SWIFT_EXTENSION(RANDARulesOfGolf))
@property (nonatomic, copy) NSString * _Nullable codename;
@property (nonatomic, copy) NSString * _Nullable difficulty;
@property (nonatomic, copy) NSString * _Nullable language;
@property (nonatomic, copy) NSDate * _Nullable lastModified;
@property (nonatomic, strong) NSSet * _Nullable questions;
@end

@class NSBundle;
@class UIViewController;

SWIFT_CLASS("_TtC16RANDARulesOfGolf30ROGBrowserNavigationController")
@interface ROGBrowserNavigationController : UINavigationController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass SWIFT_UNAVAILABLE;
@end





@class UITraitCollection;

SWIFT_CLASS("_TtC16RANDARulesOfGolf28ROGLearnNavigationController")
@interface ROGLearnNavigationController : UINavigationController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass SWIFT_UNAVAILABLE;
@end





SWIFT_CLASS("_TtC16RANDARulesOfGolf17ROGNetworkManager")
@interface ROGNetworkManager : NetworkManager
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC16RANDARulesOfGolf17ROGViewController")
@interface ROGViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIStackView;
@class UITableView;

SWIFT_CLASS("_TtC16RANDARulesOfGolf19TableViewController")
@interface TableViewController : ROGViewController
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified stackView;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC16RANDARulesOfGolf26RoundedTableViewController")
@interface RoundedTableViewController : TableViewController
- (void)viewDidLoad;
@end



@class Subrule;

@interface Rule (SWIFT_EXTENSION(RANDARulesOfGolf))
- (void)insertObject:(Subrule * _Nonnull)value inSubrulesAtIndex:(NSInteger)idx;
- (void)removeObjectFromSubrulesAtIndex:(NSInteger)idx;
- (void)insertSubrules:(NSArray<Subrule *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeSubrulesAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInSubrulesAtIndex:(NSInteger)idx withObject:(Subrule * _Nonnull)value;
- (void)replaceSubrulesAtIndexes:(NSIndexSet * _Nonnull)indexes withSubrules:(NSArray<Subrule *> * _Nonnull)values;
- (void)addSubrulesObject:(Subrule * _Nonnull)value;
- (void)removeSubrulesObject:(Subrule * _Nonnull)value;
- (void)addSubrules:(NSOrderedSet * _Nonnull)values;
- (void)removeSubrules:(NSOrderedSet * _Nonnull)values;
@end


@interface Rule (SWIFT_EXTENSION(RANDARulesOfGolf))
@property (nonatomic, copy) NSDate * _Nullable lastUpdated;
@property (nonatomic, copy) NSString * _Nullable nextClarificationCodename;
@property (nonatomic, copy) NSString * _Nullable nextRuleCodename;
@property (nonatomic, copy) NSString * _Nullable previousClarificationCodename;
@property (nonatomic, copy) NSString * _Nullable previousRuleCodename;
@property (nonatomic, copy) NSString * _Nullable purposeStatement;
@property (nonatomic, strong) NSOrderedSet * _Nullable subrules;
@end

@class UIScrollView;

SWIFT_CLASS("_TtC16RANDARulesOfGolf29ScrollableStackViewController")
@interface ScrollableStackViewController : ROGViewController
@property (nonatomic, strong) IBOutlet UIScrollView * _Null_unspecified scrollView;
@property (nonatomic, strong) IBOutlet UIStackView * _Null_unspecified stackView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS_NAMED("Section")
@interface Section : BaseRuleForm
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Section (SWIFT_EXTENSION(RANDARulesOfGolf))
@property (nonatomic, copy) NSString * _Nullable crossLinkText;
@property (nonatomic, strong) Subrule * _Nullable parent;
@end


SWIFT_CLASS("_TtC16RANDARulesOfGolf12SimpleTVCell")
@interface SimpleTVCell : UITableViewCell
- (void)awakeFromNib;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("Subrule")
@interface Subrule : BaseRuleForm
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Subrule (SWIFT_EXTENSION(RANDARulesOfGolf))
@property (nonatomic, copy) NSString * _Nullable purposeStatement;
@property (nonatomic, strong) Rule * _Nullable parent;
@property (nonatomic, strong) NSOrderedSet * _Nullable sections;
@end


@interface Subrule (SWIFT_EXTENSION(RANDARulesOfGolf))
- (void)insertObject:(Section * _Nonnull)value inSectionsAtIndex:(NSInteger)idx;
- (void)removeObjectFromSectionsAtIndex:(NSInteger)idx;
- (void)insertSections:(NSArray<Section *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeSectionsAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInSectionsAtIndex:(NSInteger)idx withObject:(Section * _Nonnull)value;
- (void)replaceSectionsAtIndexes:(NSIndexSet * _Nonnull)indexes withSections:(NSArray<Section *> * _Nonnull)values;
- (void)addSectionsObject:(Section * _Nonnull)value;
- (void)removeSectionsObject:(Section * _Nonnull)value;
- (void)addSections:(NSOrderedSet * _Nonnull)values;
- (void)removeSections:(NSOrderedSet * _Nonnull)values;
@end


SWIFT_CLASS("_TtC16RANDARulesOfGolf12SwitchTVCell")
@interface SwitchTVCell : UITableViewCell
- (void)awakeFromNib;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class NSIndexPath;

@interface TableViewController (SWIFT_EXTENSION(RANDARulesOfGolf)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)tableView:(UITableView * _Nonnull)tableView shouldHighlightRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class UIView;

@interface TableViewController (SWIFT_EXTENSION(RANDARulesOfGolf)) <UITableViewDataSource>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView estimatedHeightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView estimatedHeightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC16RANDARulesOfGolf18TextViewController")
@interface TextViewController : ROGViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end
























SWIFT_CLASS_NAMED("Video")
@interface Video : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Video (SWIFT_EXTENSION(RANDARulesOfGolf))
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable contentseries;
@property (nonatomic, copy) NSString * _Nullable entryId;
@property (nonatomic, copy) NSString * _Nullable thumbnailUrl;
@property (nonatomic, copy) NSString * _Nullable year;
@property (nonatomic) int64_t duration;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
